### ISSUE TITLE
meaning of >2px, >3px, >5px

### ISSUE THREAD

**Issue by kuwt** [XuelianCheng/LidarStereoNet#8]
I cannot find the meaning of >2px, >3px, >5px neither from KITTI nor from "Depth Map Prediction from a Single Image
using a Multi-Scale Deep Network". Could you explain where i could find the information?

**Comment by JUGGHM** [comment]
I guess it is disparity error?

**Comment by kuwt** [comment]
> I guess it is disparity error?

What is the ground truth for the comparison?

Why input lidar has invalid Abs Rel but some error in >2px,>3px and >5px?

**Comment by yiranzhong** [comment]
"What is the ground truth for the comparison?"
   --KITTI stereo provides disparity ground truth for the evaluation.

"Why input lidar has invalid Abs Rel but some error in >2px,>3px and >5px?"
   --It is because the input lidar and the ground truth are not dense. In this case, we do not evaluate the abs rel metric on the input lidar. For bad pixel rate metrics, since they compute the error ratios regardless of the densities of the inputs, we provide the results in our paper.
